### ISSUE TITLE
Which project do we want to do?

### ISSUE THREAD

**Issue by Andrew-Saarima** [theuninvited01/CS317-project#1]
Fantastic, thanks for setting this up. I was going to start work on the JavaFX calculator just for practice, and if we decide to do that for the project, all the better. I was going to first write the basic methods (add, subtract, multiply, divide) and get those to work together with some buttons, and then flesh out the rest.

**Comment by theuninvited01** [comment]
I think we were going to plan on a chat client, we need to get together and
discuss.
